---
layout: post
title: Node.js
tags: [JS]
---

[TOC]

# 箭头函数

## 基本用法

ES6 允许使用“箭头”（`=>`）定义函数。为什么叫Arrow Function？因为它的定义用的就是一个箭头：

- 如果函数返回的是一个表达式，那么可省略brackets{}和return 关键字。 注意所以一般bracket和return都是在一起出现的。箭头函数肯定是返回点东西的。只是有的时候省略了而已。

- 如果函数内部有多个语句，不是一个表达式，那么花括号会允许我们在函数中编写多个语句，但是我们需要显式地 return 来返回一些内容。

- 如果函数**只有一个参数**，那么可省略小括号 args => expression

- 无参数且内部有**多个语句**的函数一般表示为 () =>{return }

  ```js
  （1）eg
  # 标准形式，创建匿名函数，赋值给变量hello
  let hello = function() {
      return "Hello World!";
  }
  # 一个表达式，省略brackets{}和return 关键字
  let hello = () => "Hello World!";
  
  （2）eg
  let hello = (val) => "Hello " + val;
  # 有一个参数时可省略小括号
  let hello = val => "Hello " + val;
  
  ```

# Try-Catch

`try...catch` 块用于处理可能导致异常的代码，不仅仅局限于在 `try` 代码块中使用 `throw` 语句抛出错误，它也能捕获由 JavaScript 运行时产生的异常。

使用了async function的时候，会发现await只会接收promise的成功后的值，这样我们没有办法catch方法执行拿到的失败的结果，所以async函数，我们都会使用try catch结构去捕捉错误，只要try block中有错误产生，就会暂停代码执行，catch block将会获取错误。所以一般aysnc function一般都会搭配try catch使用。 可是在每一个async 函数当中使用try catch结构看起来很麻烦，代码结构也会变得很messy，所以我们可以写一个catchAsync函数，用来包裹并捕捉async异步函数。

```
module.exports = fn => {       
    return (req, res, next)=>{ 
        fn(req, res, next).catch(next);  
    };
};
```
其中以上的.catch(next)  === catch(err => next(err))
```
module.exports = fn => {       
    return (req, res, next)=>{ 
        fn(req, res, next).catch(err => next(err));  
    };
};
```
其中以上的.catch(err => next(err))将异步操作中的错误对象 err 传递给 Express 的错误处理中间件。并通过传递一个回调函数来处理错误。回调函数的参数通常是错误对象。可以使用 next(error) 将错误对象传递给Express的错误处理中间件。
1. `module.exports = fn => { ... };`: 这里使用了ES6箭头函数的语法，导出一个函数，该函数接受一个名为 `fn` 的参数。
2. `return (req, res, next) => { ... };`: 这里又返回了一个新的箭头函数，该函数将作为中间件函数被调用。
3. `fn(req, res, next).catch(next);`: 在返回的中间件函数内部，它首先调用传入的 `fn` 函数，并传入 `req`、`res` 和 `next` 三个参数。`fn` 函数可能是一个异步函数，因为使用了 `.catch()` 语法来处理可能的错误（rejected promise）。如果在 `fn` 函数的执行过程中发生了错误，它将通过 `catch()` 方法捕获错误并将错误传递给 `next` 函数，从而交由错误处理中间件处理。

综合起来，这段代码定义了一个通用的中间件函数，可以将一个异步处理函数 `fn` 包装成一个新的中间件函数，并处理该异步函数可能抛出的错误。这样，每当需要使用一个异步处理函数作为中间件时，都可以将其包装成一个具备错误处理能力的中间件。

# 回调函数

<https://chinese.freecodecamp.org/news/javascript-callback-functions/>

一个普通函数，可以传入数据，用相同的方法对不同的数据进行处理；而回调函数相当于在函数中传入一个算法，用不同的算法对相同的数据进行处理。

```
function doSomethingAsync(callback) {
  setTimeout(() => {
    try {
      // 假设在这里发生了一个错误
      throw new Error("Something went wrong!");
    } catch (err) {
      // 捕捉错误并将其传递给回调函数
      callback(err);
    }
  }, 1000);
}

// 定义回调函数（一个算法）
function errorCallback(err) {
  console.error("Error:", err.message);
}

// 定义下一个回调函数（另一个算法）
function logCallback(err) {
  console.log("Error:", err.message);
}

doSomethingAsync(errorCallback);
doSomethingAsync(logCallback);
```

经过以上的调用，我们成功地延迟了errorCallback（）和logCallback（）函数的执行，而且是在只有抛出错误的情况下才会运行，因为这两个函数为同步函数，top level的函数，如果不放在异步web api中调用，直接调用的话，是不会达到延迟运行的效果的。

# javascript中的串行与并行

[参考文档](https://juejin.cn/post/7136084613075730469)

本文来总结下js中的串行和并行。

## promise的并行

 * array.map( function(currentElement, index, arr){} )  ： map() creates a new array from calling a function for every array element.
 * 当只有第一个参数currentElement的时候，可以写成箭头函数的形式 map（t => {return }）， 此处涉及到箭头函数简写 t => {return } 。
 * 函数通过为数组每一个element调用一个函数，将计算结果返回一个新的数组，在上例子中， map（t => { return ()=>{ return } ）,在map调用的函数当中，返回一个函数(函数会返回函数)
 * 会返回一个新的函数放进数组当中，并且这些新的函数会返回一个promise，此时fnarr是一个新的函数数组，这样可以用fnarr数组再次调用map函数时，就会调用fnarr数组的元素本身（因为此时元素本身就是一个函数）

```js
const fnarr = [0, 1, 2, 3, 4, 5].map(t => {
  return () => {
    return new Promise(resolve => {
      setTimeout(() => {
        console.log(`promise${t}`)
        resolve(t)
      }, t * 1000)
    })
  }
})
```
fnarr 是一个包含多个函数的数组，每个函数返回一个 Promise 对象。当使用 map 方法对 fnarr 进行遍历，并对每个函数执行调用 fn()，返回一个 Promise 对象的数组。然后，使用 Promise.all 方法来等待所有的 Promise 对象完成。一旦所有的 Promise 对象都解析（成功），then 方法中的回调函数将会被执行，并接收一个包含所有 Promise 解析值的数组 resArr。
可以看到，尽管所有的Promise是并行执行的，但是在promise当中打印返回的结果是按照顺序排列的，这一点在某些场景下很有用。

```js
Promise.all(fnarr.map(fn => fn())).then(resArr => {
  console.log(resArr)
})
```

打印结果:

```
// 0s后
promise0
// 1s后
promise1
// 2s后
promise2
// 3s后
promise3
// 4s后
promise4
// 5s后
promise5
// 当所有promise执行完后返回所有的结果
[0, 1, 2, 3, 4, 5]
```

## promise的串行

既然要求串行，首先想到的是`async/await`实现:

```
async function run() {
  for (let i = 0; i < fnarr.length; i++) {
    const result = await fnarr[i]()
    console.log(i, result)
  }
}

run()
```

打印结果：

```
// 0s后
0 0
// 1s后
1 1
// 2s后
2 2
// 3s后
3 3
// 4s后
4 4
// 5s后
5 5
```

## promise的串行和并行

利用上面的知识，我们现在有一个需求：

- 可以并发发送请求；这样代码在多个异步处理之后一起执行，而不是一个一个去执行。
- 可以控制并发的数量：就是先发几个请求等这几个请求的结果回来后，在发另外的请求；

思路：并发可以使用`Promise.all`，而控制并发的数量，相当于是串行，可以使用async+await来做。

```
1.分组：把所有的请求按照并发数量进行分组
2.分组之后，那么就一组一组地按照顺序执行，即串行，使用async+await
3.将request分组，小组与小组之间是串行，而组内请求是并行
```

### 分组：把所有的请求按照并发数量进行分组

这个函数可以将一个数组按照指定的`max`大小进行分组，返回一个新的二维数组，其中每个子数组最多包含`max`个元素。

```
const group = (list = [], max = 0) => {
  if (!list.length) {
    return list;
  }
  let results = [];
  for (let i = 0, len = list.length; i < len; i += max) {
    results.push(list.slice(i, i + max));
  }
  return results;
};
```

### 分组之后，那么就一组一组的执行，即串行，使用async+await

```
async function sendRequest(requests = [], max = 0, callback = () => {}) {
  if (!requests.length) {
    return requests
  }
  const groupRequest = group(requests, max)
  const results = []
  // groupItems是一个小组，groupRequst是所有的小组，这样让小组与小组之间的请求是串行，而组内的请求是并行的。
  for (let groupItems of groupRequest) {
    const result = await requestHandler(groupItems, callback) //组内并行，组间串行
    results.push(result)
  }
  console.log('done', results)
  return results
}
```
groupItems是一个小组，小组内并行
```
async function requestHandler(groupItems, callback = () => {}) {
  if (!groupItems.length) {
    callback()
    return groupItems
  }
  const promiseArr = groupItems.map(fn => fn())
  const data = await Promise.allSettled(promiseArr).then(resArr => {
    resArr.map(callback)//这里callback，等待输入函数，输入的函数可以打印所有的promise的value的值
    return resArr
  })
  return data
}
```

```
const p1 = () => new Promise((resolve, reject) => setTimeout(resolve, 1000, 'p1'))
const p2 = () => Promise.resolve('p2')
const p3 = () => new Promise((resolve, reject) => setTimeout(resolve, 2000, 'p3'))
const p4 = () => Promise.resolve('p4')
const p5 = () => new Promise((resolve, reject) => setTimeout(resolve, 2000, 'p5'))
const p6 = () => Promise.resolve('p6')
const p7 = () => new Promise((resolve, reject) => setTimeout(resolve, 1000, 'p7'))
const p8 = () => Promise.resolve('p8')
const p9 = () => new Promise((resolve, reject) => setTimeout(reject, 1000, 'p9'))

const arr = [p1, p2, p3, p4, p5, p6, p7, p8, p9]

sendRequest(arr, 3, ({ reason, value }) => {
    console.log(value || reason)
})
```

打印结果:

```
// 3个为一组，每组都必须要请求结束
p1
p2
p3
// 3个为一组，每组都必须要请求结束
p4
p5
p6
// 3个为一组，每组都必须要请求结束
p7
p8
p9
// 最后的结果result
done [
  [
    { status: 'fulfilled', value: 'p1' },
    { status: 'fulfilled', value: 'p2' },
    { status: 'fulfilled', value: 'p3' }
  ],
  [
    { status: 'fulfilled', value: 'p4' },
    { status: 'fulfilled', value: 'p5' },
    { status: 'fulfilled', value: 'p6' }
  ],
  [
    { status: 'fulfilled', value: 'p7' },
    { status: 'fulfilled', value: 'p8' },
    { status: 'rejected', reason: 'p9' }
  ]
]
```

`Promise.allSettled`是一个新的API，跟`Promise.all`差不多的用法，也是接受的数组，不过不同的是`Promise.allSettled`会等所有任务结束之后才会返回结果，而`Promise.all`只要有一个`reject`就会返回结果。

同时`Promise.allSettled`返回的结果也有些不同：

- 如果对应的 promise 已经 `fulfilled`，返回 { status: 'fulfilled', value: value }
- 如果相应的 promise 已经被 `rejected`，返回 {status: 'rejected'， reason: reason }



PS： setTimeout第三个参数的作用是给回调函数传入参数，如下

```
for (var i = 0; i<4; i++) {
  setTimeout((i) => {
    console.log(i)
  }, 1000, i)
}
```

PS：Async.js (https://caolan.github.io/async/)：Async.js是一个功能强大的实用工具库，提供了许多用于处理异步JavaScript的函数。它包括`async.series`、`async.parallel`等函数，可用于按顺序或并行执行任务。
